Fix issue with crashing due to failed ticket updating
Becklyn/deploy-message-generator pull request #3
Opened 2021-12-08 16:37 UTC by glassp

Also fix issue with slack message size

2021-12-08 17:15 UTC, keichinger requested changes

2021-12-08 17:15 UTC, keichinger commented on src/Runner/SendDeployMessageRunner.php
> +            $this->io->info("The number of tickets exceeds the message length limit and can thus not be sent via the chat system.");
Instead of trying to send a single message, can we try to split the list into multiple messages (ideally a thread)?

2021-12-08 17:15 UTC, keichinger commented on src/Runner/SendDeployMessageRunner.php
> +                $this->io->warning("Failed to update ticket '{$id}'.");
```suggestion
                $this->io->warning("Failed to update ticket '{$id}': Could not find or access given ticket (typo or permissions problem?).");
```

2021-12-08 17:15 UTC, keichinger commented on src/SystemIntegration/ChatSystems/SlackChatSystem.php
> +                $listItem = \substr($listItem, 0, 3000 - 3) . '...';
I'd remove this line and do a check before trying to add the new `$listItem` and figure out whether I'm exceeding the 3000 characters. If I do, I start splitting/adding the `$listItem` (and all following entries) to a new block or even new message.

What I'd love to have is a message that is not truncated as it may open a few weird edge-cases where some tickets are supposedly listed but totally truncated off. E.g. your message is at 2999 characters and you try to add a new character. Since you can add the new item, it'd be completely truncated.

2021-12-09 08:24 UTC, glassp commented on src/SystemIntegration/ChatSystems/SlackChatSystem.php
> +                $listItem = \substr($listItem, 0, 3000 - 3) . '...';
This line in particular does only truncate the message of a single ticket if it exceeds the 3000 char limit it self e.g. `Foo-123 This is a very long ticket title that some how exceeds 3000 characters` would be truncated.

After that there is still the check if the message can be put into the current block or if it needs to go into the next block.

2021-12-15 10:30 UTC, keichinger commented on CHANGELOG.md
> +*   (bc) `ChatSystem:getChatMessage` was replaced in favor of `ChatSystem:getChatMessageThread`
```suggestion

*   (bc) `ChatSystem:getChatMessage` was replaced in favor of `ChatSystem:getChatMessageThread`
```

2021-12-15 10:31 UTC, keichinger commented on CHANGELOG.md
> +*   (bc) `ChatSystem:getChatMessage` was replaced in favor of `ChatSystem:getChatMessageThread`
```suggestion

*   (bc) `ChatSystem:getChatMessage` was replaced in favour of `ChatSystem:getChatMessageThread`
```

2021-12-15 13:46 UTC, keichinger requested changes

2021-12-15 13:46 UTC, keichinger commented on src/Runner/SendDeployMessageRunner.php
> +                $chatSystem->sendThread($thread);
This currently assumes that all chat systems have threading support. Currently with the abstraction that has been built, we're already super generic (instead of hardcoding it to Slack, since that is what we're currently using).

The threading support should be automatically used by the Slack implementation of the ChatSystem and not an explicit function. If the message is too long, it automatically becomes a thread. It could work differently on Teams or any other third party system (as an example).

2021-12-16 09:58 UTC, glassp commented on src/Runner/SendDeployMessageRunner.php
> +                $chatSystem->sendThread($thread);
Maybe the naming is not that well suited.

My intention was that in the first step the each ChatSystem generates an array of messages that is needed to send the complete deployment information.
Then in a second step the chat system should send all messages. Either as a Thread as the implementation in SlackChatSystem does. Or as a sequence of messages, which is the default implementation as defined in ChatSystem. 

If we were to use a ChatSystem that does not support threading, we would just have 2 or more consecutive messages in the given chat.

2022-03-28 08:24 UTC, keichinger commented on CHANGELOG.md
> +
```suggestion


```

2022-03-28 08:25 UTC, keichinger approved these changes

2022-03-28 08:26 UTC, merged